### ISSUE TITLE
Archive?

### ISSUE THREAD

**Issue by galinajonsson** [galinajonsson/SchistoPrev#1]
M8, is this repo of any use or can I archive?

**Comment by tompennance** [comment]
Hi G, I guess some of my NHM projects might be rekindled once back at NHM but who knows. Maybe best to archive? Thanks for checking in.

**Comment by galinajonsson** [comment]
@tompennance :+1: It'll just become read-only and can be unarchived at any point. 

See you back on Blighty soil soon! PS will reply to ur texts with a vn but I wasn't *actually* offended to clarify haha
